#!/usr/bin/env bun

import { app, $ } from "@gutenye/script.js";
import fs from "node:fs/promises";

// skip models, which is large
app
  .cmd("publish", "Publish packages")
  .add("<version>", "Version")
  .add("[packages]", "Packages", ["common,node,browser,react-native"])
  .add(async (version, packages = "common,node,browser,react-native") => {
    await updateVersion(version);
    const pkgs = packages.split(",");
    for (const pkg of pkgs) {
      await publish(pkg, version);
    }
  });

app.cmd("node example", "Run node example").add(async ({ argv }) => {
  await $`./ake start ${argv}`.cwd("packages/node/example");
});

app.cmd("browser example", "Run browser example").add(async () => {
  await $`./ake start`.cwd("packages/browser/example");
});

app.cmd("react-native example", "Run ReactNative example").add(async () => {
  await $`./ake start`.cwd("packages/react-native/example");
});

app
  .cmd("cpp example", "Run cpp example")
  .add("[path]", "Path")
  .add(async (path) => {
    if (path == null) {
      await $`./ake start`.cwd("packages/react-native/cpp/example");
    } else {
      await $`./ake start ${path}`.cwd("packages/react-native/cpp/example");
    }
  });

async function publish(pkg: string, version: string) {
  await updateVersion(version, `packages/${pkg}/package.json`);
  await $`./ake publish`.cwd(`packages/${pkg}`);
}

async function updateVersion(version: string, file = "package.json") {
  const content = await fs.readFile(file, "utf8");
  const updated = content.replace(/"version": ".*"/, `"version": "${version}"`);
  await fs.writeFile(file, updated);
}
